@startuml Node Layer - Design View

class ClientConfiguration {
    + transportType: TransportType
    + connectionTimeout: Integer
    + keepAlive: Boolean
    + bufferSize: Integer
}

interface IClientSubscriber {
    + {abstract} onConnection(connection: IConnection): Void
}

interface IClient {
    + {abstract} getConfiguration(): ClientConfiguration
    + {abstract} addSubscriber(subscriber: IClientSubscriber): Boolean
    + {abstract} removeSubscriber(subscriber: IClientSubscriber): Boolean
    + {abstract} connect(address: String, port: Integer): ConnectionId
    + {abstract} disconnect(connectionId: ConnectionId): Boolean
    + {abstract} send(connectionId: ConnectionId, data: Byte[*]): Boolean
}

class Client {
    - configuration: ClientConfiguration
    - subscribers: IClientSubscriber[*]
    - connectionFactory: IConnectionFactory
    - connectionManager: IConnectionManager
    - transportFactory: ITransportFactory
    + Client(configuration: ClientConfiguration)
}

class ServerConfiguration {
    + transportType: TransportType
    + maximumConnections: Integer
    + maximumRequestsPerSecond: Integer
    + bufferSize: Integer
}

interface IServerSubscriber {
    + {abstract} onConnection(connection: IConnection): Void
}

interface IServer {
    + {abstract} getConfiguration(): ServerConfiguration
    + {abstract} addSubscriber(subscriber: IServerSubscriber): Boolean
    + {abstract} removeSubscriber(subscriber: IServerSubscriber): Boolean
    + {abstract} start(address: String, port: Integer): Boolean
    + {abstract} stop(): void
    + {abstract} send(connectionId: ConnectionId, data: Byte[*]): Boolean
}

class Server {
    - configuration: ServerConfiguration
    - subscribers: IServerSubscriber[*]
    - connectionFactory: IConnectionFactory
    - connectionManager: IConnectionManager
    - transportFactory: ITransportFactory
    + Server(configuration:ServerConfiguration)
}

class CommunicationFactory {
    + {static} createClient(configuration: ClientConfiguration): IClient
    + {static} createServer(configuration: ServerConfiguration): IServer
}

IClient <|-- Client

Client <.. CommunicationFactory
Client "1" --* "1" ClientConfiguration
Client "1" --* "0..*" IClientSubscriber

IServer <|-- Server

Server <.. CommunicationFactory
Server "1" --* "1" ServerConfiguration
Server "1" --* "0..*" IServerSubscriber

@enduml
