@startuml Node Layer - Interface View

class ClientConfiguration {
    + transportType: TransportType
    + connectionTimeout: Integer
    + keepConnectionAlive: Boolean
    + bufferSize: Integer
}

interface IClientSubscriber {
    + {abstract} onConnection(connection: IConnection): Void
}

interface IClient {
    + {abstract} getConfiguration(): ClientConfiguration
    + {abstract} addSubscriber(subscriber: IClientSubscriber): Boolean
    + {abstract} removeSubscriber(subscriber: IClientSubscriber): Boolean
    + {abstract} connect(address: String, port: Integer): ConnectionId
    + {abstract} disconnect(connectionId: ConnectionId): Boolean
    + {abstract} send(connectionId: ConnectionId, data: Byte[*]): Boolean
    + {abstract} closeConnection(connectionId: ConnectionId): Boolean
}

class ServerConfiguration {
    + transportType: TransportType
    + maximumConnections: Integer
    + maximumRequestsPerSecond: Integer
    + bufferSize: Integer
}

interface IServerSubscriber {
    + {abstract} onConnection(connection: IConnection): Void
}

interface IServer {
    + {abstract} getConfiguration(): ServerConfiguration
    + {abstract} addSubscriber(subscriber: IServerSubscriber): Boolean
    + {abstract} removeSubscriber(subscriber: IServerSubscriber): Boolean
    + {abstract} start(address: String, port: Integer): Boolean
    + {abstract} stop(): Boolean
    + {abstract} send(connectionId: ConnectionId, data: Byte[*]): Boolean
    + {abstract} closeConnection(connectionId: ConnectionId): Boolean
}

class CommunicationFactory {
    + {static} createClient(configuration: ClientConfiguration): IClient
    + {static} createServer(configuration: ServerConfiguration): IServer
}


IClient ..> ClientConfiguration
IClient ..> IClientSubscriber
IClient <.. CommunicationFactory

IServer ..> ServerConfiguration
IServer ..> IServerSubscriber
IServer <.. CommunicationFactory

ClientConfiguration <.. CommunicationFactory

ServerConfiguration <.. CommunicationFactory

@enduml
