Node Layer
----------

Static View
^^^^^^^^^^^

.. uml:: communication/node_layer/static_view.puml
   :align: center
   :caption: Node Layer - Static View

Interface View
^^^^^^^^^^^^^^

.. uml:: communication/node_layer/interface_view.puml
   :align: center
   :caption: Node Layer - Interface View

Design View
^^^^^^^^^^^^^^

.. uml:: communication/node_layer/design_view.puml
   :align: center
   :caption: Node Layer - Design View
