file(GLOB_RECURSE CONNIX_CORE_CONFIGURATION_API_PUBLIC_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/public/ConnixCore/**/*.hpp
)

file(GLOB_RECURSE CONNIX_CORE_CONFIGURATION_API_INTERNAL_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/internal/ConnixCore/**/*.hpp
)

target_sources(connix-core PUBLIC
    ${CONNIX_CORE_CONFIGURATION_API_PUBLIC_HEADERS}
    ${CONNIX_CORE_CONFIGURATION_API_INTERNAL_HEADERS}
)

target_include_directories(connix-core PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/public
    ${CMAKE_CURRENT_SOURCE_DIR}/internal
)

install(
    DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/public/ConnixCore
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
    FILES_MATCHING PATTERN "*.hpp"
)
