file(GLOB_RECURSE CONNIX_CORE_CONFIGURATION_GMOCK_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
)

file(GLOB_RECURSE CONNIX_CORE_CONFIGURATION_GMOCK_API_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/api/ConnixCore/**/*.hpp
)

file(GLOB_RECURSE CONNIX_CORE_CONFIGURATION_GMOCK_INTERNAL_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/api-internal/ConnixCore/**/*.hpp
)

target_sources(connix-core-mocks PRIVATE
    ${CONNIX_CORE_CONFIGURATION_GMOCK_SOURCES}
    ${CONNIX_CORE_CONFIGURATION_GMOCK_API_HEADERS}
    ${CONNIX_CORE_CONFIGURATION_GMOCK_INTERNAL_HEADERS}
)

target_include_directories(connix-core-mocks PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/api
    ${CMAKE_CURRENT_SOURCE_DIR}/api-internal
)

install(
    DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/api/ConnixCore
    DESTINATION include
    FILES_MATCHING PATTERN "*.hpp"
)
