file(GLOB_RECURSE CONNIX_CORE_CONFIGURATION_GMOCK_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp
)

file(GLOB_RECURSE CONNIX_CORE_CONFIGURATION_GMOCK_PUBLIC_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/public/ConnixCore/**/*.hpp
)

file(GLOB_RECURSE CONNIX_CORE_CONFIGURATION_GMOCK_INTERNAL_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/internal/ConnixCore/**/*.hpp
)

target_sources(connix-core-mocks PRIVATE
    ${CONNIX_CORE_CONFIGURATION_GMOCK_SOURCES}
    ${CONNIX_CORE_CONFIGURATION_GMOCK_PUBLIC_HEADERS}
    ${CONNIX_CORE_CONFIGURATION_GMOCK_INTERNAL_HEADERS}
)

target_include_directories(connix-core-mocks PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/public
    ${CMAKE_CURRENT_SOURCE_DIR}/internal
)

install(
    DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/public/ConnixCore
    DESTINATION include
    FILES_MATCHING PATTERN "*.hpp"
)
