Configuration
--------------

.. sw-req:: Configuration File
    :id: [$SW_REQ CONFIGURATION_FILE]
    :desc: The Connix SHALL load configuration from a file.

.. sw-req:: Configuration JSON File
    :id: [$SW_REQ CONFIGURATION_JSON_FILE]
    :desc: Connix SHALL accept a configuration file in JSON format.

.. sw-req:: Configuration YAML File
    :id: [$SW_REQ CONFIGURATION_YAML_FILE]
    :desc: Connix SHALL accept a configuration file in YAML format.

.. sw-req:: Configuration Unsupported File
    :id: [$SW_REQ CONFIGURATION_UNSUPPORTED_FILE]
    :desc: Connix SHALL reject a configuration file that is not in JSON or YAML
           format.

.. sw-req:: Configuration Malformed File
    :id: [$SW_REQ CONFIGURATION_MALFORMED_FILE]
    :desc: Connix SHALL reject malformed configuration files.
