Execution Modes
----------------

.. sw-req:: Execution Modes
    :id: [$SW_REQ EXECUTION_MODES]
    :desc: Connix SHALL support ONETIME and PERIODIC execution modes.

.. sw-req:: Execution Modes One-Time
    :id: [$SW_REQ EXECUTION_MODES_ONETIME]
    :desc: Connix SHALL perform the configured action once and then exit when
           operating in ONETIME mode.

.. sw-req:: Execution Modes Periodic
    :id: [$SW_REQ EXECUTION_MODES_PERIODIC]
    :desc: Connix SHALL perform the configured action at each configured interval
           when operating in PERIODIC mode.

.. sw-req:: Execution Modes Built-in Scheduling
    :id: [$SW_REQ EXECUTION_MODES_BUILT_IN_SCHEDULING]
    :desc: Connix SHALL schedule ONETIME and PERIODIC actions internally without
           requiring an external scheduler.
