Operating Roles
-----------------

.. sw-req:: Operating Roles
    :id: [$SW_REQ OPERATING_ROLES]
    :desc: Connix SHALL support CLIENT, SERVER, and HYBRID operating roles.

.. sw-req:: Operating Roles Client
    :id: [$SW_REQ OPERATING_ROLES_CLIENT]
    :desc: Connix SHALL initiate outbound connections when operating in CLIENT
           role.

.. sw-req:: Operating Roles Server
    :id: [$SW_REQ OPERATING_ROLES_SERVER]
    :desc: Connix SHALL accept inbound connections when operating in SERVER role.

.. sw-req:: Operating Roles Hybrid
    :id: [$SW_REQ OPERATING_ROLES_HYBRID]
    :desc: Connix SHALL initiate outbound connections and accept inbound
           connections when operating in HYBRID role.
