Protocol Support
-----------------

.. sw-req:: Protocol Support
    :id: [$SW_REQ PROTOCOL_SUPPORT]
    :desc: Connix SHALL support TCP, UDP, and Unix Domain Socket protocols.

.. sw-req:: Protocol Support TCP
    :id: [$SW_REQ PROTOCOL_SUPPORT_TCP]
    :desc: Connix SHALL send and receive data over TCP when operating with the
           TCP protocol.

.. sw-req:: Protocol Support UDP
    :id: [$SW_REQ PROTOCOL_SUPPORT_UDP]
    :desc: Connix SHALL send and receive datagrams over UDP when operating with
           the UDP protocol.

.. sw-req:: Protocol Support UDS
    :id: [$SW_REQ PROTOCOL_SUPPORT_UDS]
    :desc: Connix SHALL send and receive data over a UDS when operating with
           the UDS protocol.
