User Interfaces
----------------

.. sw-req:: User Interfaces
    :id: [$SW_REQ USER_INTERFACES]
    :desc: Connix SHALL provide a CLI and optionally a GUI.

.. sw-req:: User Interfaces CLI
    :id: [$SW_REQ USER_INTERFACES_CLI]
    :desc: Connix SHALL provide a Command-Line Interface (CLI).

.. sw-req:: User Interfaces GUI
    :id: [$SW_REQ USER_INTERFACES_GUI]
    :desc: Connix SHALL optionally provide a Graphical User Interface (GUI).

.. sw-req:: User Interfaces GUI Provision
    :id: [$SW_REQ USER_INTERFACES_GUI_PROVISION]
    :desc: Connix SHALL provide a GUI binary when GUI support is enabled.

.. sw-req:: User Interfaces GUI Optional Build
    :id: [$SW_REQ USER_INTERFACES_GUI_OPTIONAL_BUILD]
    :desc: Connix SHALL allow GUI support to be disabled without preventing a
           compliant CLI build.

.. sw-req:: User Interfaces GUI Optional Distribution
    :id: [$SW_REQ USER_INTERFACES_GUI_OPTIONAL_DISTRIBUTION]
    :desc: Connix SHALL allow a headless release to omit the GUI binary.
