@startuml Timer Component - Static Component Diagram

[Client]

rectangle "Timer" as timer_module {
    [TimerService]
    [TimerFactory]
    [Timer]
    [Clock]
}

rectangle "Operating System" {
    [POSIX Clock / Timer APIs] as posix_clock
}

Client -right(0- TimerService
Client -(0- TimerFactory
Client -(0- Timer

TimerService -(0- Timer
TimerService -(0- Clock

TimerFactory ..> Timer : creates
TimerFactory ..> Clock : creates

Timer -(0- Clock

Clock ..> posix_clock

@enduml
