Connection Layer
----------------

Static View
^^^^^^^^^^^

.. uml:: communication/connection_layer/static_view.puml
   :align: center
   :caption: Connection Layer - Static View

Interface View
^^^^^^^^^^^^^^

.. uml:: communication/connection_layer/interface_view.puml
   :align: center
   :caption: Connection Layer - Interface View

Design View
^^^^^^^^^^^^^^

.. uml:: communication/connection_layer/design_view.puml
   :align: center
   :caption: Connection Layer - Design View
