name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  native:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: ./scripts/build_application_native.sh

  static-analysis:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Clang Format
        run: ./scripts/run_clang_format.sh --dry-run

      - name: Clang Tidy
        run: ./scripts/run_clang_tidy.sh

  documentation:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build Architecture HTML
        run: |
          cd docs/architecture
          make clean && make html

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/architecture/_build/html
