name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Clang Format
        run: ./scripts/run_clang_format.sh --dry-run

      - name: Clang Tidy
        run: ./scripts/run_clang_tidy.sh
